In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.font_manager import FontProperties

# matplotlib.style.use('ggplot')
import matplotlib
# matplotlib.style.use('ggplot')
#matplotlib.style.use('default')
from numpy import *
import numpy as np
%matplotlib inline
%pylab inline
pylab.rcParams['figure.figsize'] = (8, 6)
import subprocess,shlex,sys,select,re,StringIO
def readHive(sql):
    text = ''
    err = ''
    cmd = shlex.split('hive -e '+ '"set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;'+sql+'"')
    print >>sys.stderr, cmd
    sys.stderr.flush()
    proc = subprocess.Popen(cmd, bufsize=0, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    while proc.poll() is None:
        ins, outs, errs = select.select([proc.stdout, proc.stderr], [], [])
        if proc.stdout in ins:
            text += proc.stdout.read()
        if proc.stderr in ins:
            c = proc.stderr.read(1)
            if c == '\n':
                print >>sys.stderr, err
                sys.stderr.flush()
                err = ''
            else:
                err += c
    text += proc.stdout.read()
    print >>sys.stderr, proc.stderr.read()
    sys.stderr.flush()
    header, content = text.split('\n',1)
    header = re.sub('\w*\.','', header)
    return pd.read_table(StringIO.StringIO(header+'\n'+content), error_bad_lines = False)

def f(x):
    x=str(x)
    tmp=x.split("//")
    if len(tmp)<=1:
        return x
    return '.'.join(x.strip().split('//')[1].split('/')[0].split('.')[-3:])

Populating the interactive namespace from numpy and matplotlib

WARNING: pylab import has clobbered these variables: ['f']
`%matplotlib` prevents importing * from pylab and numpy

In [4]:
v0919=readHive("select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=19 group by vendor_id,fraud_flag")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=19 group by vendor_id,fraud_flag']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160920163744_08d4caa2-a8ab-4f12-a93a-60b0dca8bd92
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_650464, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_650464/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_650464
Hadoop job information for Stage-1: number of mappers: 234; number of reducers: 1
2016-09-20 16:38:29,655 Stage-1 map = 0%,  reduce = 0%
2016-09-20 16:38:46,815 Stage-1 map = 2%,  reduce = 0%, Cumulative CPU 16.15 sec
2016-09-20 16:38:49,045 Stage-1 map = 5%,  reduce = 0%, Cumulative CPU 44.28 sec
2016-09-20 16:38:50,097 Stage-1 map = 7%,  reduce = 0%, Cumulative CPU 60.98 sec
2016-09-20 16:38:51,227 Stage-1 map = 9%,  reduce = 0%, Cumulative CPU 78.41 sec
2016-09-20 16:38:52,280 Stage-1 map = 11%,  reduce = 0%, Cumulative CPU 92.21 sec
2016-09-20 16:38:53,357 Stage-1 map = 14%,  reduce = 0%, Cumulative CPU 143.73 sec
2016-09-20 16:38:54,524 Stage-1 map = 17%,  reduce = 0%, Cumulative CPU 179.99 sec
2016-09-20 16:38:55,652 Stage-1 map = 22%,  reduce = 0%, Cumulative CPU 237.22 sec
2016-09-20 16:38:56,705 Stage-1 map = 27%,  reduce = 0%, Cumulative CPU 317.53 sec
2016-09-20 16:38:57,827 Stage-1 map = 35%,  reduce = 0%, Cumulative CPU 419.61 sec
2016-09-20 16:38:58,905 Stage-1 map = 43%,  reduce = 0%, Cumulative CPU 508.29 sec
2016-09-20 16:39:00,003 Stage-1 map = 52%,  reduce = 0%, Cumulative CPU 612.54 sec
2016-09-20 16:39:01,065 Stage-1 map = 66%,  reduce = 0%, Cumulative CPU 788.38 sec
2016-09-20 16:39:02,126 Stage-1 map = 73%,  reduce = 0%, Cumulative CPU 884.79 sec
2016-09-20 16:39:03,439 Stage-1 map = 78%,  reduce = 0%, Cumulative CPU 922.96 sec
2016-09-20 16:39:04,598 Stage-1 map = 85%,  reduce = 0%, Cumulative CPU 1020.27 sec
2016-09-20 16:39:05,651 Stage-1 map = 88%,  reduce = 0%, Cumulative CPU 1049.76 sec
2016-09-20 16:39:06,854 Stage-1 map = 91%,  reduce = 0%, Cumulative CPU 1072.5 sec
2016-09-20 16:39:07,937 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 1116.37 sec
2016-09-20 16:39:11,175 Stage-1 map = 97%,  reduce = 0%, Cumulative CPU 1124.17 sec
2016-09-20 16:39:12,225 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 1138.2 sec
2016-09-20 16:39:14,418 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 1144.66 sec
2016-09-20 16:39:19,992 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1160.73 sec
2016-09-20 16:39:34,417 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 1163.7 sec
MapReduce Total cumulative CPU time: 19 minutes 23 seconds 700 msec
Ended Job = job_1471856463785_650464
MapReduce Jobs Launched:
34  Reduce: 1   Cumulative CPU: 1163.7 sec   HDFS Read: 219589731 HDFS Write: 394 SUCCESS
Total MapReduce CPU Time Spent: 19 minutes 23 seconds 700 msec
OK
Time taken: 111.521 seconds, Fetched: 41 row(s)

In [22]:
v0818=readHive("select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=8 and day=18 group by vendor_id,fraud_flag")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=8 and day=18 group by vendor_id,fraud_flag']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160920165048_5dff9dcd-e636-4a75-833d-3dfa15dd5761
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_650631, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_650631/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_650631
Hadoop job information for Stage-1: number of mappers: 238; number of reducers: 1
2016-09-20 16:51:22,701 Stage-1 map = 0%,  reduce = 0%
2016-09-20 16:51:37,997 Stage-1 map = 1%,  reduce = 0%, Cumulative CPU 5.68 sec
2016-09-20 16:51:39,102 Stage-1 map = 4%,  reduce = 0%, Cumulative CPU 23.02 sec
2016-09-20 16:51:40,195 Stage-1 map = 6%,  reduce = 0%, Cumulative CPU 39.36 sec
2016-09-20 16:51:41,264 Stage-1 map = 8%,  reduce = 0%, Cumulative CPU 61.46 sec
2016-09-20 16:51:42,332 Stage-1 map = 14%,  reduce = 0%, Cumulative CPU 130.74 sec
2016-09-20 16:51:43,377 Stage-1 map = 18%,  reduce = 0%, Cumulative CPU 198.63 sec
2016-09-20 16:51:44,421 Stage-1 map = 22%,  reduce = 0%, Cumulative CPU 256.93 sec
2016-09-20 16:51:45,527 Stage-1 map = 27%,  reduce = 0%, Cumulative CPU 323.04 sec
2016-09-20 16:51:46,619 Stage-1 map = 37%,  reduce = 0%, Cumulative CPU 487.33 sec
2016-09-20 16:51:47,680 Stage-1 map = 42%,  reduce = 0%, Cumulative CPU 545.21 sec
2016-09-20 16:51:48,745 Stage-1 map = 47%,  reduce = 0%, Cumulative CPU 641.24 sec
2016-09-20 16:51:49,787 Stage-1 map = 52%,  reduce = 0%, Cumulative CPU 693.76 sec
2016-09-20 16:51:50,921 Stage-1 map = 58%,  reduce = 0%, Cumulative CPU 800.68 sec
2016-09-20 16:51:52,008 Stage-1 map = 63%,  reduce = 0%, Cumulative CPU 855.63 sec
2016-09-20 16:51:53,262 Stage-1 map = 68%,  reduce = 0%, Cumulative CPU 905.19 sec
2016-09-20 16:51:54,514 Stage-1 map = 75%,  reduce = 0%, Cumulative CPU 1000.05 sec
2016-09-20 16:51:55,627 Stage-1 map = 81%,  reduce = 0%, Cumulative CPU 1054.4 sec
2016-09-20 16:51:56,731 Stage-1 map = 87%,  reduce = 0%, Cumulative CPU 1101.19 sec
2016-09-20 16:51:57,788 Stage-1 map = 88%,  reduce = 0%, Cumulative CPU 1122.16 sec
2016-09-20 16:51:58,961 Stage-1 map = 89%,  reduce = 0%, Cumulative CPU 1126.37 sec
2016-09-20 16:52:00,068 Stage-1 map = 94%,  reduce = 0%, Cumulative CPU 1181.03 sec
2016-09-20 16:52:01,117 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 1195.85 sec
2016-09-20 16:52:03,338 Stage-1 map = 97%,  reduce = 0%, Cumulative CPU 1204.31 sec
2016-09-20 16:52:04,423 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 1205.66 sec
2016-09-20 16:52:05,468 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 1226.48 sec
2016-09-20 16:52:07,725 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1226.94 sec
2016-09-20 16:52:18,517 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 1230.81 sec
MapReduce Total cumulative CPU time: 20 minutes 30 seconds 810 msec
Ended Job = job_1471856463785_650631
MapReduce Jobs Launched:
Stage-Stage-1: Map: 238  Reduce: 1   Cumulative CPU: 1230.81 sec   HDFS Read: 241212062 HDFS Write: 459 SUCCESS
Total MapReduce CPU Time Spent: 20 minutes 30 seconds 810 msec
OK
Time taken: 92.287 seconds, Fetched: 47 row(s)

    vendor_id  fraud_flag   _c2_x   _c2_y         r
0           1         NaN   19614   22804  0.860112
1           1         0.0    1178   22804  0.051658
2           1         1.0    1948   22804  0.085424
3           1         5.0      64   22804  0.002807
4           2         NaN  256250  288088  0.889485
5           2         0.0    3305  288088  0.011472
6           2         1.0   21642  288088  0.075123
7           2         5.0    6891  288088  0.023920
8           5         NaN    3838    5662  0.677852
9           5         0.0    1376    5662  0.243024
10          5         1.0     420    5662  0.074179
11          5         5.0      28    5662  0.004945
12          8         NaN      13      13  1.000000
13          9         NaN  228763  271741  0.841842
14          9         0.0   29309  271741  0.107856
15          9         1.0   12628  271741  0.046471
16          9         5.0    1041  271741  0.003831
17         10         NaN       5       5  1.000000
18         13         NaN      14      14  1.000000
19         15         NaN   25838   27450  0.941275
20         15         0.0     228   27450  0.008306
21         15         1.0    1268   27450  0.046193
22         15         5.0     116   27450  0.004226
23         20         NaN    1088    1088  1.000000
24         21         NaN   45187   52274  0.864426
25         21         0.0    3421   52274  0.065444
26         21         1.0    3447   52274  0.065941
27         21         5.0     219   52274  0.004189
28         24         NaN   38931   43485  0.895274
29         24         1.0    4361   43485  0.100287
30         24         5.0     193   43485  0.004438
31         31         NaN     354     371  0.954178
32         31         1.0      17     371  0.045822
33         37         NaN     348     354  0.983051
34         37         1.0       6     354  0.016949
35         38         NaN   13604   20468  0.664647
36         38         2.0    6864   20468  0.335353
37         40         NaN   41764   41764  1.000000
38         56         NaN       1       1  1.000000
39         61         NaN      40      40  1.000000
40         72         NaN      53      53  1.000000

In [27]:
v0918=readHive("select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=18 group by vendor_id,fraud_flag")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=18 group by vendor_id,fraud_flag']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160920170340_b18a4d64-8c8e-4931-bf12-0647a904d653
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_650804, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_650804/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_650804
Hadoop job information for Stage-1: number of mappers: 239; number of reducers: 1
2016-09-20 17:04:24,595 Stage-1 map = 0%,  reduce = 0%
2016-09-20 17:04:36,364 Stage-1 map = 1%,  reduce = 0%, Cumulative CPU 7.4 sec
2016-09-20 17:04:37,419 Stage-1 map = 5%,  reduce = 0%, Cumulative CPU 26.64 sec
2016-09-20 17:04:38,610 Stage-1 map = 6%,  reduce = 0%, Cumulative CPU 40.82 sec
2016-09-20 17:04:39,712 Stage-1 map = 9%,  reduce = 0%, Cumulative CPU 56.28 sec
2016-09-20 17:04:41,005 Stage-1 map = 16%,  reduce = 0%, Cumulative CPU 124.67 sec
2016-09-20 17:04:42,189 Stage-1 map = 23%,  reduce = 0%, Cumulative CPU 202.1 sec
2016-09-20 17:04:43,253 Stage-1 map = 31%,  reduce = 0%, Cumulative CPU 294.99 sec
2016-09-20 17:04:44,295 Stage-1 map = 39%,  reduce = 0%, Cumulative CPU 390.3 sec
2016-09-20 17:04:45,441 Stage-1 map = 52%,  reduce = 0%, Cumulative CPU 558.31 sec
2016-09-20 17:04:46,534 Stage-1 map = 63%,  reduce = 0%, Cumulative CPU 709.44 sec
2016-09-20 17:04:47,582 Stage-1 map = 77%,  reduce = 0%, Cumulative CPU 896.25 sec
2016-09-20 17:04:48,777 Stage-1 map = 85%,  reduce = 0%, Cumulative CPU 985.43 sec
2016-09-20 17:04:49,907 Stage-1 map = 90%,  reduce = 0%, Cumulative CPU 1071.12 sec
2016-09-20 17:04:50,962 Stage-1 map = 93%,  reduce = 0%, Cumulative CPU 1113.09 sec
2016-09-20 17:04:52,222 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 1146.32 sec
2016-09-20 17:04:53,380 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 1164.8 sec
2016-09-20 17:04:54,425 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 1176.28 sec
2016-09-20 17:04:56,837 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1176.76 sec
2016-09-20 17:05:04,990 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 1180.93 sec
MapReduce Total cumulative CPU time: 19 minutes 40 seconds 930 msec
Ended Job = job_1471856463785_650804
MapReduce Jobs Launched:
ap: 239  Reduce: 1   Cumulative CPU: 1180.93 sec   HDFS Read: 137271015 HDFS Write: 400 SUCCESS
Total MapReduce CPU Time Spent: 19 minutes 40 seconds 930 msec
OK
Time taken: 85.349 seconds, Fetched: 43 row(s)

In [35]:
v0920=readHive("select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=20 group by vendor_id,fraud_flag")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=20 group by vendor_id,fraud_flag']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160921104808_adaf94d4-d11e-478d-9f7f-a88ec83570d1
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_667640, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_667640/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_667640
Hadoop job information for Stage-1: number of mappers: 233; number of reducers: 1
2016-09-21 10:48:55,924 Stage-1 map = 0%,  reduce = 0%
2016-09-21 10:49:12,803 Stage-1 map = 1%,  reduce = 0%, Cumulative CPU 4.6 sec
2016-09-21 10:49:15,720 Stage-1 map = 3%,  reduce = 0%, Cumulative CPU 23.88 sec
2016-09-21 10:49:16,766 Stage-1 map = 5%,  reduce = 0%, Cumulative CPU 34.67 sec
2016-09-21 10:49:17,802 Stage-1 map = 6%,  reduce = 0%, Cumulative CPU 43.88 sec
2016-09-21 10:49:18,837 Stage-1 map = 7%,  reduce = 0%, Cumulative CPU 59.82 sec
2016-09-21 10:49:20,080 Stage-1 map = 10%,  reduce = 0%, Cumulative CPU 97.18 sec
2016-09-21 10:49:21,113 Stage-1 map = 16%,  reduce = 0%, Cumulative CPU 140.42 sec
2016-09-21 10:49:22,150 Stage-1 map = 22%,  reduce = 0%, Cumulative CPU 235.59 sec
2016-09-21 10:49:23,187 Stage-1 map = 29%,  reduce = 0%, Cumulative CPU 312.75 sec
2016-09-21 10:49:24,227 Stage-1 map = 38%,  reduce = 0%, Cumulative CPU 406.37 sec
2016-09-21 10:49:25,309 Stage-1 map = 47%,  reduce = 0%, Cumulative CPU 494.2 sec
2016-09-21 10:49:26,356 Stage-1 map = 55%,  reduce = 0%, Cumulative CPU 553.97 sec
2016-09-21 10:49:27,392 Stage-1 map = 62%,  reduce = 0%, Cumulative CPU 635.08 sec
2016-09-21 10:49:28,430 Stage-1 map = 70%,  reduce = 0%, Cumulative CPU 719.09 sec
2016-09-21 10:49:29,463 Stage-1 map = 75%,  reduce = 0%, Cumulative CPU 787.94 sec
2016-09-21 10:49:30,500 Stage-1 map = 78%,  reduce = 0%, Cumulative CPU 816.77 sec
2016-09-21 10:49:31,743 Stage-1 map = 83%,  reduce = 0%, Cumulative CPU 875.25 sec
2016-09-21 10:49:32,863 Stage-1 map = 87%,  reduce = 0%, Cumulative CPU 917.92 sec
2016-09-21 10:49:33,896 Stage-1 map = 91%,  reduce = 0%, Cumulative CPU 954.02 sec
2016-09-21 10:49:34,927 Stage-1 map = 94%,  reduce = 0%, Cumulative CPU 995.86 sec
2016-09-21 10:49:35,958 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 1018.24 sec
2016-09-21 10:49:36,993 Stage-1 map = 97%,  reduce = 0%, Cumulative CPU 1031.22 sec
2016-09-21 10:49:39,054 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 1032.53 sec
2016-09-21 10:49:42,365 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 1049.38 sec
2016-09-21 10:49:46,485 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1057.67 sec
2016-09-21 10:50:02,148 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 1060.78 sec
MapReduce Total cumulative CPU time: 17 minutes 40 seconds 780 msec
Ended Job = job_1471856463785_667640
MapReduce Jobs Launched:
 Map: 233  Reduce: 1   Cumulative CPU: 1060.78 sec   HDFS Read: 97062506 HDFS Write: 397 SUCCESS
Total MapReduce CPU Time Spent: 17 minutes 40 seconds 780 msec
OK
Time taken: 117.4 seconds, Fetched: 44 row(s)

In [38]:
v0921=readHive("select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=21 group by vendor_id,fraud_flag")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=21 group by vendor_id,fraud_flag']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160921160237_05951626-c170-430a-8916-2d20076e053f
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_672743, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_672743/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_672743
Hadoop job information for Stage-1: number of mappers: 228; number of reducers: 1
2016-09-21 16:03:16,674 Stage-1 map = 0%,  reduce = 0%
2016-09-21 16:03:32,016 Stage-1 map = 1%,  reduce = 0%, Cumulative CPU 8.3 sec
2016-09-21 16:03:34,153 Stage-1 map = 2%,  reduce = 0%, Cumulative CPU 14.01 sec
2016-09-21 16:03:37,484 Stage-1 map = 4%,  reduce = 0%, Cumulative CPU 33.23 sec
2016-09-21 16:03:40,843 Stage-1 map = 5%,  reduce = 0%, Cumulative CPU 47.45 sec
2016-09-21 16:03:41,967 Stage-1 map = 6%,  reduce = 0%, Cumulative CPU 55.1 sec
2016-09-21 16:03:43,019 Stage-1 map = 7%,  reduce = 0%, Cumulative CPU 64.46 sec
2016-09-21 16:03:45,148 Stage-1 map = 9%,  reduce = 0%, Cumulative CPU 89.85 sec
2016-09-21 16:03:46,196 Stage-1 map = 11%,  reduce = 0%, Cumulative CPU 109.38 sec
2016-09-21 16:03:47,307 Stage-1 map = 13%,  reduce = 0%, Cumulative CPU 134.39 sec
2016-09-21 16:03:48,402 Stage-1 map = 14%,  reduce = 0%, Cumulative CPU 154.57 sec
2016-09-21 16:03:49,448 Stage-1 map = 15%,  reduce = 0%, Cumulative CPU 160.78 sec
2016-09-21 16:03:50,563 Stage-1 map = 17%,  reduce = 0%, Cumulative CPU 185.56 sec
2016-09-21 16:03:51,628 Stage-1 map = 19%,  reduce = 0%, Cumulative CPU 195.56 sec
2016-09-21 16:03:52,827 Stage-1 map = 21%,  reduce = 0%, Cumulative CPU 215.7 sec
2016-09-21 16:03:53,937 Stage-1 map = 23%,  reduce = 0%, Cumulative CPU 242.17 sec
2016-09-21 16:03:54,971 Stage-1 map = 25%,  reduce = 0%, Cumulative CPU 253.99 sec
2016-09-21 16:03:56,050 Stage-1 map = 26%,  reduce = 0%, Cumulative CPU 266.17 sec
2016-09-21 16:03:57,099 Stage-1 map = 27%,  reduce = 0%, Cumulative CPU 277.78 sec
2016-09-21 16:03:58,272 Stage-1 map = 30%,  reduce = 0%, Cumulative CPU 306.89 sec
2016-09-21 16:03:59,364 Stage-1 map = 34%,  reduce = 0%, Cumulative CPU 352.9 sec
2016-09-21 16:04:00,402 Stage-1 map = 37%,  reduce = 0%, Cumulative CPU 381.36 sec
2016-09-21 16:04:01,581 Stage-1 map = 39%,  reduce = 0%, Cumulative CPU 401.49 sec
2016-09-21 16:04:03,682 Stage-1 map = 41%,  reduce = 0%, Cumulative CPU 430.12 sec
2016-09-21 16:04:04,883 Stage-1 map = 44%,  reduce = 0%, Cumulative CPU 457.65 sec
2016-09-21 16:04:05,947 Stage-1 map = 47%,  reduce = 0%, Cumulative CPU 478.8 sec
2016-09-21 16:04:06,979 Stage-1 map = 49%,  reduce = 0%, Cumulative CPU 502.13 sec
2016-09-21 16:04:08,113 Stage-1 map = 50%,  reduce = 0%, Cumulative CPU 516.69 sec
2016-09-21 16:04:09,181 Stage-1 map = 53%,  reduce = 0%, Cumulative CPU 540.37 sec
2016-09-21 16:04:10,366 Stage-1 map = 54%,  reduce = 0%, Cumulative CPU 555.77 sec
2016-09-21 16:04:11,447 Stage-1 map = 57%,  reduce = 0%, Cumulative CPU 581.01 sec
2016-09-21 16:04:12,480 Stage-1 map = 59%,  reduce = 0%, Cumulative CPU 607.4 sec
2016-09-21 16:04:13,632 Stage-1 map = 62%,  reduce = 0%, Cumulative CPU 634.17 sec
2016-09-21 16:04:14,733 Stage-1 map = 64%,  reduce = 0%, Cumulative CPU 657.97 sec
2016-09-21 16:04:15,768 Stage-1 map = 66%,  reduce = 0%, Cumulative CPU 677.78 sec
2016-09-21 16:04:16,912 Stage-1 map = 68%,  reduce = 0%, Cumulative CPU 690.14 sec
2016-09-21 16:04:18,000 Stage-1 map = 71%,  reduce = 0%, Cumulative CPU 722.45 sec
2016-09-21 16:04:19,161 Stage-1 map = 72%,  reduce = 0%, Cumulative CPU 735.88 sec
2016-09-21 16:04:21,288 Stage-1 map = 74%,  reduce = 0%, Cumulative CPU 747.53 sec
2016-09-21 16:04:23,426 Stage-1 map = 75%,  reduce = 0%, Cumulative CPU 753.58 sec
2016-09-21 16:04:24,484 Stage-1 map = 76%,  reduce = 0%, Cumulative CPU 762.43 sec
2016-09-21 16:04:26,628 Stage-1 map = 79%,  reduce = 0%, Cumulative CPU 781.24 sec
2016-09-21 16:04:27,706 Stage-1 map = 80%,  reduce = 0%, Cumulative CPU 803.0 sec
2016-09-21 16:04:28,741 Stage-1 map = 81%,  reduce = 0%, Cumulative CPU 808.69 sec
2016-09-21 16:04:30,965 Stage-1 map = 82%,  reduce = 0%, Cumulative CPU 817.76 sec
2016-09-21 16:04:33,096 Stage-1 map = 83%,  reduce = 0%, Cumulative CPU 831.49 sec
2016-09-21 16:04:34,183 Stage-1 map = 84%,  reduce = 0%, Cumulative CPU 838.7 sec
2016-09-21 16:04:36,331 Stage-1 map = 85%,  reduce = 0%, Cumulative CPU 851.99 sec
2016-09-21 16:04:37,413 Stage-1 map = 86%,  reduce = 0%, Cumulative CPU 856.9 sec
2016-09-21 16:04:38,452 Stage-1 map = 87%,  reduce = 0%, Cumulative CPU 865.68 sec
2016-09-21 16:04:39,481 Stage-1 map = 88%,  reduce = 0%, Cumulative CPU 870.56 sec
2016-09-21 16:04:41,690 Stage-1 map = 89%,  reduce = 0%, Cumulative CPU 878.21 sec
2016-09-21 16:04:44,906 Stage-1 map = 90%,  reduce = 0%, Cumulative CPU 886.35 sec
2016-09-21 16:04:49,369 Stage-1 map = 91%,  reduce = 0%, Cumulative CPU 893.61 sec
2016-09-21 16:04:51,606 Stage-1 map = 92%,  reduce = 0%, Cumulative CPU 898.9 sec
2016-09-21 16:04:52,693 Stage-1 map = 93%,  reduce = 0%, Cumulative CPU 901.18 sec
2016-09-21 16:04:53,733 Stage-1 map = 94%,  reduce = 0%, Cumulative CPU 911.22 sec
2016-09-21 16:04:54,767 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 919.87 sec
2016-09-21 16:04:56,944 Stage-1 map = 97%,  reduce = 0%, Cumulative CPU 927.54 sec
2016-09-21 16:04:57,996 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 929.68 sec
2016-09-21 16:05:00,252 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 940.12 sec
2016-09-21 16:05:02,321 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 945.9 sec
2016-09-21 16:05:14,169 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 948.78 sec
MapReduce Total cumulative CPU time: 15 minutes 48 seconds 780 msec
Ended Job = job_1471856463785_672743
MapReduce Jobs Launched:
228  Reduce: 1   Cumulative CPU: 948.78 sec   HDFS Read: 54854424 HDFS Write: 363 SUCCESS
Total MapReduce CPU Time Spent: 15 minutes 48 seconds 780 msec
OK
Time taken: 157.873 seconds, Fetched: 41 row(s)

In [39]:
vsrc=v0921
vsum=vsrc[['vendor_id','_c2']].groupby(['vendor_id']).sum().reset_index()
vsum
join=pd.merge(vsrc,vsum,on='vendor_id',how='inner')
join['r']=join['_c2_x']/join['_c2_y']
join

    vendor_id  fraud_flag  _c2_x  _c2_y         r
0           1         NaN   7616   9013  0.845002
1           1         0.0    908   9013  0.100743
2           1         1.0    478   9013  0.053035
3           1         5.0     11   9013  0.001220
4           2         NaN  43550  53810  0.809329
5           2         0.0   1709  53810  0.031760
6           2         1.0   1477  53810  0.027448
7           2         5.0   7074  53810  0.131463
8           5         NaN    499    850  0.587059
9           5         0.0    128    850  0.150588
10          5         1.0    223    850  0.262353
11          8         NaN     13     13  1.000000
12          9         NaN  20561  21938  0.937232
13          9         0.0    659  21938  0.030039
14          9         1.0    467  21938  0.021287
15          9         5.0    251  21938  0.011441
16         10         NaN      7      8  0.875000
17         10         1.0      1      8  0.125000
18         13         NaN      3      3  1.000000
19         15         NaN  14774  15405  0.959039
20         15         0.0     97  15405  0.006297
21         15         1.0    487  15405  0.031613
22         15         5.0     47  15405  0.003051
23         16         NaN     15     15  1.000000
24         20         NaN    552    552  1.000000
25         21         NaN  18483  19372  0.954109
26         21         0.0     29  19372  0.001497
27         21         1.0    769  19372  0.039696
28         21         5.0     91  19372  0.004698
29         24         NaN  13829  14419  0.959082
30         24         1.0    475  14419  0.032943
31         24         5.0    115  14419  0.007976
32         31         NaN    397    402  0.987562
33         31         1.0      5    402  0.012438
34         33         NaN      1      1  1.000000
35         37         NaN    168    223  0.753363
36         37         0.0     51    223  0.228700
37         37         1.0      4    223  0.017937
38         38         NaN     54     74  0.729730
39         38         2.0     20     74  0.270270
40         40         NaN   5709   5709  1.000000

In [53]:
c920=readHive("select vendor_id,hour, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=20 group by vendor_id,fraud_flag,hour")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id,hour, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=20 group by vendor_id,fraud_flag,hour']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160921193303_5e98fbc1-6325-4985-b6fd-9f04ac87e30e
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_676372, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_676372/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_676372
Hadoop job information for Stage-1: number of mappers: 233; number of reducers: 1
2016-09-21 19:33:28,505 Stage-1 map = 0%,  reduce = 0%
2016-09-21 19:33:39,008 Stage-1 map = 2%,  reduce = 0%, Cumulative CPU 6.63 sec
2016-09-21 19:33:40,041 Stage-1 map = 4%,  reduce = 0%, Cumulative CPU 20.09 sec
2016-09-21 19:33:41,085 Stage-1 map = 7%,  reduce = 0%, Cumulative CPU 36.06 sec
2016-09-21 19:33:42,122 Stage-1 map = 12%,  reduce = 0%, Cumulative CPU 93.02 sec
2016-09-21 19:33:43,158 Stage-1 map = 20%,  reduce = 0%, Cumulative CPU 165.33 sec
2016-09-21 19:33:44,192 Stage-1 map = 31%,  reduce = 0%, Cumulative CPU 260.79 sec
2016-09-21 19:33:45,224 Stage-1 map = 48%,  reduce = 0%, Cumulative CPU 431.35 sec
2016-09-21 19:33:46,260 Stage-1 map = 60%,  reduce = 0%, Cumulative CPU 591.46 sec
2016-09-21 19:33:47,306 Stage-1 map = 73%,  reduce = 0%, Cumulative CPU 798.2 sec
2016-09-21 19:33:48,352 Stage-1 map = 81%,  reduce = 0%, Cumulative CPU 904.39 sec
2016-09-21 19:33:49,382 Stage-1 map = 90%,  reduce = 0%, Cumulative CPU 1008.08 sec
2016-09-21 19:33:50,411 Stage-1 map = 95%,  reduce = 0%, Cumulative CPU 1041.53 sec
2016-09-21 19:33:51,443 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 1075.55 sec
2016-09-21 19:33:53,501 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 1079.63 sec
2016-09-21 19:34:01,801 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1091.54 sec
2016-09-21 19:34:12,135 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 1094.94 sec
MapReduce Total cumulative CPU time: 18 minutes 14 seconds 940 msec
Ended Job = job_1471856463785_676372
MapReduce Jobs Launched:
ap: 233  Reduce: 1   Cumulative CPU: 1094.94 sec   HDFS Read: 97086064 HDFS Write: 7686 SUCCESS
Total MapReduce CPU Time Spent: 18 minutes 14 seconds 940 msec
OK
Time taken: 69.934 seconds, Fetched: 686 row(s)

In [51]:
c921=readHive("select vendor_id,hour, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=21 group by vendor_id,fraud_flag,hour")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id,hour, fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=21 group by vendor_id,fraud_flag,hour']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160921193123_bf805e93-3cd2-4a5b-92fb-dac1684e0933
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_676350, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_676350/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_676350
Hadoop job information for Stage-1: number of mappers: 231; number of reducers: 1
2016-09-21 19:31:48,014 Stage-1 map = 0%,  reduce = 0%
2016-09-21 19:32:00,040 Stage-1 map = 3%,  reduce = 0%, Cumulative CPU 16.68 sec
2016-09-21 19:32:01,077 Stage-1 map = 6%,  reduce = 0%, Cumulative CPU 32.57 sec
2016-09-21 19:32:02,111 Stage-1 map = 9%,  reduce = 0%, Cumulative CPU 49.73 sec
2016-09-21 19:32:03,163 Stage-1 map = 17%,  reduce = 0%, Cumulative CPU 109.82 sec
2016-09-21 19:32:04,198 Stage-1 map = 27%,  reduce = 0%, Cumulative CPU 198.25 sec
2016-09-21 19:32:05,232 Stage-1 map = 41%,  reduce = 0%, Cumulative CPU 332.04 sec
2016-09-21 19:32:06,265 Stage-1 map = 57%,  reduce = 0%, Cumulative CPU 479.23 sec
2016-09-21 19:32:07,300 Stage-1 map = 67%,  reduce = 0%, Cumulative CPU 616.92 sec
2016-09-21 19:32:08,335 Stage-1 map = 81%,  reduce = 0%, Cumulative CPU 810.6 sec
2016-09-21 19:32:09,368 Stage-1 map = 88%,  reduce = 0%, Cumulative CPU 868.15 sec
2016-09-21 19:32:10,399 Stage-1 map = 93%,  reduce = 0%, Cumulative CPU 895.06 sec
2016-09-21 19:32:11,430 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 915.07 sec
2016-09-21 19:32:13,491 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 925.46 sec
2016-09-21 19:32:14,520 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 931.51 sec
2016-09-21 19:32:18,641 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 936.6 sec
2016-09-21 19:32:31,207 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 940.21 sec
MapReduce Total cumulative CPU time: 15 minutes 40 seconds 210 msec
Ended Job = job_1471856463785_676350
MapReduce Jobs Launched:
ap: 231  Reduce: 1   Cumulative CPU: 940.21 sec   HDFS Read: 77519252 HDFS Write: 6166 SUCCESS
Total MapReduce CPU Time Spent: 15 minutes 40 seconds 210 msec
OK
Time taken: 68.787 seconds, Fetched: 554 row(s)

In [63]:
clean921=readHive("select vendor_id,fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=21 group by vendor_id,fraud_flag")
clean920=readHive("select vendor_id,fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=20 group by vendor_id,fraud_flag")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id,fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=21 group by vendor_id,fraud_flag']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160922095914_fba4c899-913a-4411-b069-e75efeec635f
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_689094, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_689094/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_689094
Hadoop job information for Stage-1: number of mappers: 235; number of reducers: 1
2016-09-22 09:59:33,746 Stage-1 map = 0%,  reduce = 0%
2016-09-22 09:59:45,584 Stage-1 map = 6%,  reduce = 0%, Cumulative CPU 46.72 sec
2016-09-22 09:59:46,719 Stage-1 map = 17%,  reduce = 0%, Cumulative CPU 157.39 sec
2016-09-22 09:59:47,759 Stage-1 map = 43%,  reduce = 0%, Cumulative CPU 440.86 sec
2016-09-22 09:59:48,793 Stage-1 map = 62%,  reduce = 0%, Cumulative CPU 645.39 sec
2016-09-22 09:59:49,827 Stage-1 map = 79%,  reduce = 0%, Cumulative CPU 836.07 sec
2016-09-22 09:59:50,860 Stage-1 map = 89%,  reduce = 0%, Cumulative CPU 943.59 sec
2016-09-22 09:59:51,892 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 1010.45 sec
2016-09-22 09:59:52,927 Stage-1 map = 97%,  reduce = 0%, Cumulative CPU 1036.53 sec
2016-09-22 09:59:53,959 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 1044.89 sec
2016-09-22 10:00:42,591 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 1045.64 sec
2016-09-22 10:01:42,595 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 1051.46 sec
2016-09-22 10:02:14,589 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1052.63 sec
2016-09-22 10:02:24,843 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 1055.55 sec
MapReduce Total cumulative CPU time: 17 minutes 35 seconds 550 msec
Ended Job = job_1471856463785_689094
MapReduce Jobs Launched:
ap: 235  Reduce: 1   Cumulative CPU: 1055.55 sec   HDFS Read: 115368317 HDFS Write: 416 SUCCESS
Total MapReduce CPU Time Spent: 17 minutes 35 seconds 550 msec
OK
Time taken: 191.541 seconds, Fetched: 45 row(s)

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id,fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=20 group by vendor_id,fraud_flag']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160922100230_188ca197-432e-4903-b646-294520b493cb
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_689129, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_689129/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_689129
Hadoop job information for Stage-1: number of mappers: 233; number of reducers: 1
2016-09-22 10:02:59,925 Stage-1 map = 0%,  reduce = 0%
2016-09-22 10:03:13,524 Stage-1 map = 1%,  reduce = 0%, Cumulative CPU 7.02 sec
2016-09-22 10:03:14,774 Stage-1 map = 4%,  reduce = 0%, Cumulative CPU 23.81 sec
2016-09-22 10:03:15,810 Stage-1 map = 8%,  reduce = 0%, Cumulative CPU 47.18 sec
2016-09-22 10:03:16,854 Stage-1 map = 13%,  reduce = 0%, Cumulative CPU 90.32 sec
2016-09-22 10:03:17,895 Stage-1 map = 16%,  reduce = 0%, Cumulative CPU 129.7 sec
2016-09-22 10:03:18,937 Stage-1 map = 22%,  reduce = 0%, Cumulative CPU 189.0 sec
2016-09-22 10:03:19,974 Stage-1 map = 30%,  reduce = 0%, Cumulative CPU 280.98 sec
2016-09-22 10:03:21,010 Stage-1 map = 38%,  reduce = 0%, Cumulative CPU 374.37 sec
2016-09-22 10:03:22,054 Stage-1 map = 47%,  reduce = 0%, Cumulative CPU 491.31 sec
2016-09-22 10:03:23,087 Stage-1 map = 55%,  reduce = 0%, Cumulative CPU 590.98 sec
2016-09-22 10:03:24,126 Stage-1 map = 64%,  reduce = 0%, Cumulative CPU 696.99 sec
2016-09-22 10:03:25,384 Stage-1 map = 74%,  reduce = 0%, Cumulative CPU 793.65 sec
2016-09-22 10:03:26,417 Stage-1 map = 79%,  reduce = 0%, Cumulative CPU 869.8 sec
2016-09-22 10:03:27,448 Stage-1 map = 81%,  reduce = 0%, Cumulative CPU 886.15 sec
2016-09-22 10:03:28,480 Stage-1 map = 84%,  reduce = 0%, Cumulative CPU 927.1 sec
2016-09-22 10:03:29,511 Stage-1 map = 90%,  reduce = 0%, Cumulative CPU 986.41 sec
2016-09-22 10:03:30,554 Stage-1 map = 92%,  reduce = 0%, Cumulative CPU 1009.55 sec
2016-09-22 10:03:31,585 Stage-1 map = 93%,  reduce = 0%, Cumulative CPU 1020.47 sec
2016-09-22 10:03:32,617 Stage-1 map = 94%,  reduce = 0%, Cumulative CPU 1028.81 sec
2016-09-22 10:03:35,714 Stage-1 map = 95%,  reduce = 0%, Cumulative CPU 1046.79 sec
2016-09-22 10:03:36,749 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 1075.35 sec
2016-09-22 10:03:37,779 Stage-1 map = 97%,  reduce = 0%, Cumulative CPU 1082.7 sec
2016-09-22 10:03:38,813 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 1087.94 sec
2016-09-22 10:03:42,927 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 1090.85 sec
2016-09-22 10:03:53,436 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1105.0 sec
2016-09-22 10:04:05,110 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 1107.69 sec
MapReduce Total cumulative CPU time: 18 minutes 27 seconds 690 msec
Ended Job = job_1471856463785_689129
MapReduce Jobs Launched:
ap: 233  Reduce: 1   Cumulative CPU: 1107.69 sec   HDFS Read: 97062506 HDFS Write: 397 SUCCESS
Total MapReduce CPU Time Spent: 18 minutes 27 seconds 690 msec
OK
Time taken: 97.151 seconds, Fetched: 44 row(s)

In [67]:
clean921.query('vendor_id in (2,9,15,21)')

    vendor_id  fraud_flag    _c2
4           2         NaN  88400
5           2         0.0   6603
6           2         1.0   3404
7           2         5.0  19050
12          9         NaN  60210
13          9         0.0   3317
14          9         1.0   1805
15          9         5.0   7032
19         15         NaN  21881
20         15         0.0    111
21         15         1.0    799
22         15         5.0     61
27         21         NaN  53206
28         21         0.0    112
29         21         1.0   2308
30         21         5.0    307

In [69]:
clean922=readHive("select vendor_id,fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=22 group by vendor_id,fraud_flag")

['hive', '-e', 'set mapreduce.job.queuename=zampda_job;set hive.cli.print.header=true;select vendor_id,fraud_flag,count(1) from fraud_free.dclkv2 where year=2016 and month=9 and day=22 group by vendor_id,fraud_flag']

Logging initialized using configuration in file:/var/bh/lib/apache-hive-1.2.1-bin/conf/hive-log4j.properties
Query ID = changbin_20160922172217_833f26ff-35d8-4588-b7bb-695e9098f670
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1471856463785_695888, Tracking URL = http://TS-NN-001:50030/proxy/application_1471856463785_695888/
Kill Command = /var/bh/hadoop/bin/hadoop job  -kill job_1471856463785_695888
Hadoop job information for Stage-1: number of mappers: 227; number of reducers: 1
2016-09-22 17:23:26,751 Stage-1 map = 0%,  reduce = 0%
2016-09-22 17:23:41,766 Stage-1 map = 1%,  reduce = 0%, Cumulative CPU 5.43 sec
2016-09-22 17:23:42,804 Stage-1 map = 4%,  reduce = 0%, Cumulative CPU 32.34 sec
2016-09-22 17:23:43,849 Stage-1 map = 9%,  reduce = 0%, Cumulative CPU 74.29 sec
2016-09-22 17:23:44,888 Stage-1 map = 19%,  reduce = 0%, Cumulative CPU 162.42 sec
2016-09-22 17:23:45,925 Stage-1 map = 29%,  reduce = 0%, Cumulative CPU 241.51 sec
2016-09-22 17:23:46,962 Stage-1 map = 41%,  reduce = 0%, Cumulative CPU 343.29 sec
2016-09-22 17:23:48,006 Stage-1 map = 49%,  reduce = 0%, Cumulative CPU 422.39 sec
2016-09-22 17:23:49,042 Stage-1 map = 58%,  reduce = 0%, Cumulative CPU 518.37 sec
2016-09-22 17:23:50,081 Stage-1 map = 70%,  reduce = 0%, Cumulative CPU 644.25 sec
2016-09-22 17:23:51,121 Stage-1 map = 77%,  reduce = 0%, Cumulative CPU 725.53 sec
2016-09-22 17:23:52,159 Stage-1 map = 80%,  reduce = 0%, Cumulative CPU 763.14 sec
2016-09-22 17:23:53,190 Stage-1 map = 84%,  reduce = 0%, Cumulative CPU 799.21 sec
2016-09-22 17:23:54,222 Stage-1 map = 86%,  reduce = 0%, Cumulative CPU 819.55 sec
2016-09-22 17:23:55,252 Stage-1 map = 87%,  reduce = 0%, Cumulative CPU 824.98 sec
2016-09-22 17:23:56,285 Stage-1 map = 90%,  reduce = 0%, Cumulative CPU 853.54 sec
2016-09-22 17:23:57,316 Stage-1 map = 91%,  reduce = 0%, Cumulative CPU 866.93 sec
2016-09-22 17:23:58,348 Stage-1 map = 92%,  reduce = 0%, Cumulative CPU 883.63 sec
2016-09-22 17:23:59,380 Stage-1 map = 93%,  reduce = 0%, Cumulative CPU 889.33 sec
2016-09-22 17:24:00,410 Stage-1 map = 94%,  reduce = 0%, Cumulative CPU 907.89 sec
2016-09-22 17:24:01,441 Stage-1 map = 96%,  reduce = 0%, Cumulative CPU 921.83 sec
2016-09-22 17:24:02,471 Stage-1 map = 97%,  reduce = 0%, Cumulative CPU 928.86 sec
2016-09-22 17:24:04,538 Stage-1 map = 98%,  reduce = 0%, Cumulative CPU 947.02 sec
2016-09-22 17:24:06,602 Stage-1 map = 99%,  reduce = 0%, Cumulative CPU 952.9 sec
2016-09-22 17:24:45,128 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 963.04 sec
2016-09-22 17:24:53,580 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 966.29 sec
MapReduce Total cumulative CPU time: 16 minutes 6 seconds 290 msec
Ended Job = job_1471856463785_695888
MapReduce Jobs Launched:
 Reduce: 1   Cumulative CPU: 966.29 sec   HDFS Read: 71176825 HDFS Write: 406 SUCCESS
Total MapReduce CPU Time Spent: 16 minutes 6 seconds 290 msec
OK
Time taken: 157.34 seconds, Fetched: 45 row(s)

In [70]:
clean922.query('vendor_id in (2,9,15,21)')

    vendor_id  fraud_flag    _c2
4           2         NaN  49221
5           2         0.0   1107
6           2         1.0   1452
7           2         5.0   3268
12          9         NaN  38372
13          9         0.0   2429
14          9         1.0    768
15          9         2.0      3
16          9         5.0   2271
19         15         NaN  16403
20         15         0.0    304
21         15         1.0    467
22         15         5.0     11
26         21         NaN  23161
27         21         0.0     61
28         21         1.0    730
29         21         5.0    147